<?php
/**
 * Created by mulat.
 * User: mulat
 * Date: 07.05.2015
 * Time: 13:17
 */
namespace backend\modules\purchase\components\fancybox;

use yii\web\AssetBundle;

class MousewheelAsset extends AssetBundle
{
    /**
     * Unique value to set an empty asset via Yii AssetManager configuration.
     */
    const EMPTY_ASSET = 'N0/@$$3T$';
    public $sourcePath = '@backend/modules/purchase/components/fancybox';

    public $js = self::EMPTY_ASSET;

    public $css = [];

    public $depends = [
        'yii\web\JqueryAsset',
        'backend\modules\purchase\components\fancybox\FancyBoxAsset',
    ];

    public function init()
    {
        if ($this->js === self::EMPTY_ASSET) {
            $this->js = [
              //  'lib/jquery.mousewheel.' . (YII_DEBUG ? '' : 'min.') . 'js'
            ];
            $this->js = [
                'lib/jquery.mousewheel.pack.js',
            ];
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
